---
-
  hosts: all
  sudo: yes
  tasks:
    -
      name: apt-update
      apt: update_cache=true cache_valid_time=3600
      sudo: true
    -
      name: install packages
      action: apt pkg={{ item }} state=installed
      sudo: true
      with_items:
        - git
        - curl
        - postgresql-9.1
        - postgresql-client-9.1
        - libpq-dev
      notify: restart postgresql
    -
      name: update pd_hba.conf
      copy: src="files/pg_hba.conf" dest="/etc/postgresql/9.1/main/pg_hba.conf"
      sudo: true